framework:
    messenger:
        failure_transport: failed

        transports:

            external_messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\Serializer\ExternalJsonMessengerSerializer
                options:
                    auto_setup: false
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: from_external
                    queues:
                        messages_from_external:
                            binding_keys: [from_external]

            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_high_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    delay: 500
                options:
                    exchange:
                        name: high
                        type: direct
                    queues:
                        high: ~

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: normal
                    queues:
                        messages_normal:
                            binding_keys: [normal]

            failed: 'doctrine://default?queue_name=failed'


        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            'App\Messenger\Message\GenerateRandomNumberMessage': async_high_priority
            'App\Messenger\Message\RemoveRandIntMessage': async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
