framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: hhh
                    queues:
                        messages_normal:
                            binding_keys: [hhh]
#                        messages_high:
#                            binding_keys: [hhh]

            failed: 'doctrine://default?queue_name=failed'
        routing:
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Event\Dispatcher\Message\Message: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
