nelmio_api_doc:
    documentation:
        info:
            title: Pizza app
            description: Pizza app for test cqrs ddd
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
